### ISSUE TITLE
Execute frontier in Overlay

### ISSUE THREAD

**Issue by gliargovas** [binpash/hs#50]
As of now, we execute the frontier in the main workspace. This solution however does not guarantee correctness of the Overlay file systems running on top of the workspace's filesystem.

To solve this, we need to execute the frontier inside an Overlay too, and commit the result only when absolutely safe to do so (when no Overlays are running on the worskapce).

#### 1. **Batches/Window:** 
One simple solution (although certainly not optimal) is to use a modified version of our initial batch approach (used in the HotOS paper). We can split the commands of the script in batches and speculate/optimize inside the batches. Between each batch execution we can commit the results. We can specify a `window` or `batch_size` property in the scheduler, which will reflect the number of commands to execute and speculate about. After all the batch commands have finished executing we can resolve the dependencies between them. Small batch size -> good for scripts with plenty of dependent commands; Large batch size -> independent command scripts.

The batches themselves can be split and executed in parallel given that few dependencies exist.

(?) Script preprocessing could also help us decide how to split the batches maybe?

➕ Pros
- Simple to implement
- Average case should not be much slower compared to continuous approach

➖ Cons
- Significantly slower worst case
- Tricky to select batch size

#### 2. Batches with Recursive Overlays:

Instead of just using plain batches as in approach 1, we can employ a more intelligent system that makes use of recursive overlays. For each command an overlay filesystem is created on top of the overlay of its predecessor.

➕ Pros
-  Faster 

➖ Cons
- Higher complexity
- Need to re-execute all children of failed cmds (?)
- Multiple copies for a single command (?)

#### 3. One single large recursive Overlay:

Same but one single recursive Overlay chain (Not sure if this is feasible at all).

**Comment by angelhof** [comment]
Other things that can optimize the solution
- Incremental dependencies
- killing overlays

After a meeting with @gliargovas and @ericzty we decided to go for a strategy that kills overlays as soon as the frontier overlay is done. This guarantees best worst case time, but could potentially miss some speculation. Afterwards, the goal is to try for a recursive overlay strategy to make this more effective.
