### ISSUE TITLE
Same commands are not treated as separate

### ISSUE THREAD

**Issue by gliargovas** [binpash/hs#7]
The following example will result in an error:
```
grep foo in1 > out1
grep foo in1 > out2
```
This is because even though we use the cmd id as a key in the beginning,
we use the actual cmd as a key during tracing in the `cmd_exec_info` dictionary.

Solutions:
1. Use cmd ID everywhere
2. Support multiple values per key in the `cmd_exec_info` dict.

**Comment by angelhof** [comment]
I think it makes sense to use the cmdID everywhere (in general it is good to key things based on ids and not values) :)
